### PR TITLE
Fix state lables in NexusWriter

### LINKED ISSUE #969: [BUG] State description of a concatenated alignment can make written Nexus file unreadable
**Describe the bug**
When concatenating two or more alignments using `concatenate()`, the state description (or state space) of the first alignment is applied to the concatenated alignment. 
This means that, when using `writeNexus()` to write the concatenated alignment on a Nexus file, the symbols specified in the Nexus header will be limited to the states seen in the first original alignment. 
If the first original alignment has a smaller state space than other alignments in the concatenation, then the written Nexus file will be unreadable by `readDiscreteCharacterData()`, as an "invalid state specified" error will appear.

**To Reproduce**
```
# create taxa
for (i in 1:10) { taxa[i] = taxon("Taxon"+i) }

# simulate a tree
tau ~ dnUniformTimeTree(rootAge=1, taxa=taxa)
       
# 2-states substitution model
Q_2 := fnJC(2)

# 6-states substitution model
Q_6 := fnJC(6)
       
# Generate alignments
Alignment1 ~ dnPhyloCTMC(tree=tau, Q=Q_2, nSites = 100, type="Standard", coding="variable")
Alignment2 ~ dnPhyloCTMC(tree=tau, Q=Q_6, nSites = 100, type="Standard", coding="variable")

# Concatenate alignments in both orders
ConcatenatedAlignment_12 := concatenate(Alignment1, Alignment2)
ConcatenatedAlignment_21 := concatenate(Alignment2, Alignment1)

# Check state descriptions for concatenated alignments
ConcatenatedAlignment_12.getStateDescriptions()
ConcatenatedAlignment_21.getStateDescriptions()
       
# Write Nexus files
writeNexus(filename="concatenated_12.nex", ConcatenatedAlignment_12)
writeNexus(filename="concatenated_21.nex", ConcatenatedAlignment_21)

# Try to read Nexus files
data_12 = readDiscreteCharacterData("concatenated_12.nex") #This gives an "Invalid state specified" error
data_21 = readDiscreteCharacterData("concatenated_21.nex")

```
**Expected behavior**
Written Nexus files should be readable no matter what order the original alignments were concatenated in.

**Computer info**
RevBayes version 1.3.2

### PR DESCRIPTION
**Pull request by basantakhakurel**
Fixes #969 

### Problem
When concatenating character matrices with different state spaces, the NexusWriter only used the state labels from the first matrix. 
This meant that the `symbols=` field in the NEXUS file was incomplete (missing the complete state labels) causing the written file to be unreadable. 

### Changes
**`src/core/io/NexusWriter.cpp`**
- Instead of reading state labels from only the first character, now iterates over all included characters and collects a union of all state symbols, ensuring completeness.

**`src/revlanguage/datatypes/phylogenetics/characterdata/RlAbstractHomologousDiscreteCharacterData.cpp`**
- Previously only returned the states from the first matrix. Now builds a union similar to NexusWriter fix to return the complete state labels.

Added a new test script (`test_writeNexus`) that checks if the nexus files are being written properly. 

(Also added .zed in `.gitignore`)

### CODE REVIEW

File: src/core/io/NexusWriter.cpp [hunk 1]
```diff
@@ -74,17 +74,34 @@ void NexusWriter::writeNexusBlock(const AbstractHomologousDiscreteCharacterData
...
+                {
+                    unique_labels.insert(char_labels[j]);
+                }
+            }
+        }
+        
+        // write the set as state symbols to the NEXUS format block
         out_stream << "symbols=\"";
-        for (size_t i = 0; i < labels.size(); ++i)
+        for (std::set<char>::iterator it = unique_labels.begin(); it != unique_labels.end(); ++it)
```
Comment (bredelings) [inline src/core/io/NexusWriter.cpp]: for(char label: unique_labels)

**Review by bredelings — APPROVED** [review]

**Review by davidcerny — APPROVED** [review]
