### PR TITLE
Prevent loss of integer precision in MC^3

### LINKED ISSUE #651: MC^3 may attempt to swap non-existent chains
@ms609's dataset [950_ns_ki](https://github.com/mk-nt/950_ns_ki) throws an interesting error that apparently stems from the loss of precision that occurs when converting from `size_t` to `int`. In this example, the script specifies 8 chains per run, which are indexed from 0 to 7. However, because of this issue, the function `Mcmcmc::swapNeighborChains()` at one point picks a non-existent chain with an index of 8 for a swap, producing an invalid access error:

> I rebuilt the latest development RevBayes on my HPC and ran an mpi run with [950_ns_ki](https://github.com/mk-nt/950_ns_ki).  I saw:
> 
> ```
> RevBayes version (1.2.5-preview)
> Build from development (rapture-3215-g906131) on Wed  4 Dec 15:45:35 GMT 2024
> MPI enabled: using 128 processes.
> 
> Visit the website www.RevBayes.com for more information about RevBayes.
> 
> RevBayes is free software released under the GPL license, version 3. Type 'license()' for details.
> 
> To quit RevBayes type 'quit()' or 'q()'.
> 
> 
> Unknown user setting with key 'collapseSampledAncestors'.
> [ ... repeated many times (!) ... ]
> Unknown user setting with key 'collapseSampledAncestors'.
> source("mcmcmc.Rev")
>    Processing file "mcmcmc.Rev"
> Timestamp:      2024    339     59397
>    Successfully read one character matrix from file 'project950.neo.nex'
>    Successfully read one character matrix from file 'project950.trans.nex'
>    Processing file "ns_ki.Rev"
> 5       characters in partition with    2       states
> 1       characters in partition with    3       states
>    Processing of file "ns_ki.Rev" completed
>   - Created MCMCMC object
> 
>    Running burn-in phase of Monte Carlo sampler for 3000 iterations.
>    This simulation runs 2 independent replicates.
>    The MCMCMC simulator runs 1 cold chain and 7 heated chains.
>    The simulator uses 7 different moves in a random move schedule with 14.875 moves per iteration
> 
> 
> Progress:
> 
> 0---------------25---------------50---------------75--------------100
> ***********************************************[login2:3972680:0:3972680] Caught signal 11 (Segmentation fault: add     ress not mapped to object at address 0x8)
> [login2:3972690:0:3972690] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> [login2:3972671:0:3972671] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> [login2:3972691:0:3972691] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> [login2:3972685:0:3972685] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> [login2:3972694:0:3972694] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> [login2:3972696:0:3972696] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> [login2:3972678:0:3972678] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
> BFD: Dwarf Error: Can't find .debug_ranges section.
> [ ... repeated many times ... ]
> BFD: Dwarf Error: Can't find .debug_ranges section.
> ==== backtrace (tid:3972685) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972685] *** Process received signal ***
> [login2:3972685] Signal: Segmentation fault (11)
> [login2:3972685] Signal code:  (-6)
> [login2:3972685] Failing at address: 0x8b4e003c9e4d
> [login2:3972685] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7f5669e39d20]
> [login2:3972685] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972685] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972685] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972685] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972685] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972685] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972685] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972685] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972685] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972685] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972685] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972685] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972685] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972685] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972685] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972685] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972685] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f5668ed27e5]
> [login2:3972685] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972685] *** End of error message ***
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> ==== backtrace (tid:3972690) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972690] *** Process received signal ***
> [login2:3972690] Signal: Segmentation fault (11)
> [login2:3972690] Signal code:  (-6)
> [login2:3972690] Failing at address: 0x8b4e003c9e52
> [login2:3972690] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7f3496070d20]
> [login2:3972690] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972690] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972690] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972690] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972690] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972690] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972690] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972690] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972690] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972690] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972690] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972690] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972690] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972690] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972690] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972690] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972690] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f34951097e5]
> [login2:3972690] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972690] *** End of error message ***
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> ==== backtrace (tid:3972691) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972691] *** Process received signal ***
> [login2:3972691] Signal: Segmentation fault (11)
> [login2:3972691] Signal code:  (-6)
> [login2:3972691] Failing at address: 0x8b4e003c9e53
> [login2:3972691] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7f4b93188d20]
> [login2:3972691] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972691] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972691] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972691] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972691] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972691] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972691] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972691] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972691] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972691] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972691] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972691] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972691] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972691] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972691] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972691] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972691] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f4b922217e5]
> [login2:3972691] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972691] *** End of error message ***
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> BFD: Dwarf Error: Can't find .debug_ranges section.
> ==== backtrace (tid:3972694) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972694] *** Process received signal ***
> [login2:3972694] Signal: Segmentation fault (11)
> [login2:3972694] Signal code:  (-6)
> [login2:3972694] Failing at address: 0x8b4e003c9e56
> [login2:3972694] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7f5ded589d20]
> [login2:3972694] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972694] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972694] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972694] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972694] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972694] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972694] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972694] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972694] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972694] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972694] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972694] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972694] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972694] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972694] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972694] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972694] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f5dec6227e5]
> [login2:3972694] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972694] *** End of error message ***
> ==== backtrace (tid:3972671) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972671] *** Process received signal ***
> [login2:3972671] Signal: Segmentation fault (11)
> [login2:3972671] Signal code:  (-6)
> [login2:3972671] Failing at address: 0x8b4e003c9e3f
> [login2:3972671] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7f689dc0ad20]
> [login2:3972671] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972671] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972671] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972671] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972671] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972671] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972671] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972671] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972671] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972671] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972671] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972671] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972671] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972671] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972671] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972671] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972671] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f689cca37e5]
> [login2:3972671] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972671] *** End of error message ***
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> ==== backtrace (tid:3972680) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972680] *** Process received signal ***
> [login2:3972680] Signal: Segmentation fault (11)
> [login2:3972680] Signal code:  (-6)
> [login2:3972680] Failing at address: 0x8b4e003c9e48
> [login2:3972680] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7fc20968ad20]
> [login2:3972680] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972680] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972680] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972680] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972680] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972680] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972680] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972680] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972680] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972680] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972680] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972680] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972680] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972680] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972680] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972680] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972680] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7fc2087237e5]
> [login2:3972680] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972680] *** End of error message ***
> ==== backtrace (tid:3972678) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972678] *** Process received signal ***
> [login2:3972678] Signal: Segmentation fault (11)
> [login2:3972678] Signal code:  (-6)
> [login2:3972678] Failing at address: 0x8b4e003c9e46
> [login2:3972678] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7efc355eed20]
> [login2:3972678] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972678] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972678] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972678] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972678] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972678] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972678] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972678] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972678] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972678] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972678] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972678] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972678] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972678] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972678] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972678] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972678] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7efc346877e5]
> [login2:3972678] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972678] *** End of error message ***
> ==== backtrace (tid:3972696) ====
>  0 0x0000000000012d20 __funlockfile()  :0
>  1 0x0000000001a0539c RevBayesCore::Mcmcmc::swapGivenChains()  ???:0
>  2 0x0000000001a06418 RevBayesCore::Mcmcmc::nextCycle()  ???:0
>  3 0x00000000019c399d RevBayesCore::MonteCarloAnalysis::burnin()  ???:0
>  4 0x00000000016b946b RevLanguage::MonteCarloAnalysis::executeMethod()  ???:0
>  5 0x0000000000fb87fd RevLanguage::MemberProcedure::execute()  ???:0
>  6 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
>  7 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
>  8 0x000000000140177d yyparse()  ???:0
>  9 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 10 0x0000000001582798 RevLanguage::Func_source::execute()  ???:0
> 11 0x000000000141982e RevLanguage::SyntaxFunctionCall::evaluateContent()  ???:0
> 12 0x0000000000e96431 RevLanguage::Parser::execute()  ???:0
> 13 0x000000000140177d yyparse()  ???:0
> 14 0x0000000000e9734c RevLanguage::Parser::processCommand()  ???:0
> 15 0x000000000066f2d1 RevLanguageMain::startRevLanguageEnvironment()  ???:0
> 16 0x0000000000626446 main()  ???:0
> 17 0x000000000003a7e5 __libc_start_main()  ???:0
> 18 0x000000000066074e _start()  ???:0
> =================================
> [login2:3972696] *** Process received signal ***
> [login2:3972696] Signal: Segmentation fault (11)
> [login2:3972696] Signal code:  (-6)
> [login2:3972696] Failing at address: 0x8b4e003c9e58
> [login2:3972696] [ 0] /lib64/libpthread.so.0(+0x12d20)[0x7f1ee6402d20]
> [login2:3972696] [ 1] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a0539c]
> [login2:3972696] [ 2] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1a06418]
> [login2:3972696] [ 3] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x19c399d]
> [login2:3972696] [ 4] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x16b946b]
> [login2:3972696] [ 5] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xfb87fd]
> [login2:3972696] [ 6] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972696] [ 7] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972696] [ 8] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972696] [ 9] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972696] [10] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x1582798]
> [login2:3972696] [11] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x141982e]
> [login2:3972696] [12] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe96431]
> [login2:3972696] [13] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x140177d]
> [login2:3972696] [14] ../revbayes/projects/cmake/build-mpi/rb-mpi[0xe9734c]
> [login2:3972696] [15] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66f2d1]
> [login2:3972696] [16] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x626446]
> [login2:3972696] [17] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f1ee549b7e5]
> [login2:3972696] [18] ../revbayes/projects/cmake/build-mpi/rb-mpi[0x66074e]
> [login2:3972696] *** End of error message ***
> --------------------------------------------------------------------------
> mpirun noticed that process rank 43 with PID 0 on node login2 exited on signal 11 (Segmentation fault).
> --------------------------------------------------------------------------
> ``` 

 _Originally posted by @ms609 in [#609](https://github.com/revbayes/revbayes/issues/609#issuecomment-2517965603)_

### PR DESCRIPTION
**Pull request by davidcerny**
This should fix #651.

It'd be great to add a test for this, but the analysis where this issue popped up keeps crashing even after it is fixed – now for a different reason that no longer has to do with MC^3.

### CODE REVIEW

**Comment by bredelings** [comment]
Um.... for some reason when I reviewed/merged this I didn't see all the changes :grimacing: 
So now I have some questions...

File: src/core/analysis/mcmc/Mcmcmc.cpp [hunk 1]
```diff
@@ -1136,14 +1136,14 @@ void Mcmcmc::setHeatsInitial(const std::vector<double>& ht)
         throw RbException()<<"Heat vector contains "<<ht.size()<<" heats, but there are "<<num_chains<<" chains.";
 
     // 2. Check that the heats are non-zero
-    for(int i=0; i<int(ht.size()); i++)
+    for(size_t i=0; i<ht.size(); i++)
```
Comment (bredelings) [inline src/core/analysis/mcmc/Mcmcmc.cpp:1139]: I think this is wrong.  The point here is to convert `ht.size()` to a signed type, so that if `ht.size() == 0` the result doesn't overflow.

File: src/core/analysis/mcmc/Mcmcmc.cpp [hunk 2]
```diff
@@ -1136,14 +1136,14 @@ void Mcmcmc::setHeatsInitial(const std::vector<double>& ht)
...
     {
         if (not (ht[i] > 0.0))
             throw RbException()<<"Heat "<<i+1<<" is "<<ht[i]<<", but should be > 0";
     }
 
     // 3. Check that the heats are sorted with the largest heat first (== smallest temperature first).
-    for(int i=0;i<int(ht.size())-1;i++)
+    for(size_t i=0;i<ht.size()-1;i++)
```
Comment (bredelings) [inline src/core/analysis/mcmc/Mcmcmc.cpp:1146]: Also here.

File: src/core/analysis/mcmc/Mcmcmc.cpp [hunk 3]
```diff
@@ -1312,7 +1312,7 @@ void Mcmcmc::synchronizeValues( bool likelihood_only )
         {
             if ( pid == pid_per_chain[i] )
             {
-                MPI_Send(&results[i], 1, MPI_DOUBLE, (int)active_PID, 0, MPI_COMM_WORLD);
+                MPI_Send(&results[i], 1, MPI_DOUBLE, active_PID, 0, MPI_COMM_WORLD);
```
Comment (bredelings) [inline src/core/analysis/mcmc/Mcmcmc.cpp:1315]: what type was `active_PID` before it was converted to `int`?

Comment (davidcerny) [reply src/core/analysis/mcmc/Mcmcmc.cpp:1315]: It is of type `size_t`.

File: src/core/analysis/mcmc/Mcmcmc.cpp (hunk 1 above)
Comment (davidcerny) [reply src/core/analysis/mcmc/Mcmcmc.cpp:1139]: Ah, okay. I'm not sure if you can undo the merge, but if so, I'm happy to push a commit to restore `int` here (and the other place you point out below). If not, one of us can open another PR to that effect.

Comment (bredelings) [reply src/core/analysis/mcmc/Mcmcmc.cpp:1139]: Actually this one is fine.  Its the one below (`ht.size()-1`) that is the issue.

File: src/core/analysis/mcmc/Mcmcmc.cpp (hunk 2 above)
Comment (bredelings) [reply src/core/analysis/mcmc/Mcmcmc.cpp:1146]: Here you can do something like `std::int64_t(ht.size())`, and that avoids the issue with `-1` wrapping around and becoming a large, positive number.

Comment (bredelings) [reply src/core/analysis/mcmc/Mcmcmc.cpp:1146]: So here I think we can avoid casting to a signed type by just avoiding subtraction. We can check `i+1 <ht.size()`, which might make more sense anyway if we are trying to check that `ht[i+1]` is valid.

File: src/core/analysis/mcmc/Mcmcmc.cpp (hunk 3 above)
Comment (bredelings) [reply src/core/analysis/mcmc/Mcmcmc.cpp:1315]: Hmm.... let's keep an eye on that...
If it keeps happening, we could revert this change and then re-introduce pieces of it.
