### PR TITLE
Make sure the tip time moves use the right `node_index` in each MCMC run

### LINKED ISSUE #858: [BUG] Skyline FBD analyses produce compiler-dependent output
**Describe the bug**
Fossilized Birth-Death (FBD) analyses in general are wonky in RevBayes, since they produce different output on different platforms: it's why we [special-case](https://github.com/revbayes/revbayes/blob/cbe72b0372cf2c869d951293b383181bacdb9e99/.github/workflows/build.yml#L312) our test runner to ignore the FBD test output produced on macOS or Windows. However, it turns out that skyline FBD analyses – in which one or more of the rate parameters can vary through time in a piecewise-constant manner – are even more wonky, since their output differs between different compilers on the same platform.

Until recently, all of our FBD tests only specified constant-rate analyses, but in PR #845, a skyline FBD test was added. [GitHub Actions](https://github.com/revbayes/revbayes/actions/runs/18109603397/job/51553905219) show that this test produces consistent output under the following OS/compiler combos:

- Ubuntu 22.04, GCC 10
- Ubuntu 24.04, GCC 11 (no MPI)
- Ubuntu 22.04, GCC 12
- Ubuntu 24.04, GCC 13
- Ubuntu 24.04, GCC 15 (incl. with `buildtype: debug-optimized`)
- Ubuntu 24.04, Clang 15

The first few lines of the log file here looks as follows:

```
Iteration	Posterior	Likelihood	Prior	branch_rates_morpho	extinction_rate	origin_time	psi[1]	psi[2]	psi[3]	psi[4]	psi[5]	speciation_rate
0	-7477.243	-7240.708	-236.5342	0.04483802	0.0352606	3.150825	8.13918	6.77304	12.8996	6.34757	0.762531	0.07298359
5	-3153.135	-3085.028	-68.1064	0.1031445	0.7223114	2.051456	1.39008	0.867115	1.91905	0.307876	6.90674	0.9265235
10	-3148.35	-3083.157	-65.19248	0.1072652	0.7644451	2.033234	6.55731	0.134521	4.06573	1.05351	6.6125	1.13495
```

But under Ubuntu 24.04, GCC 14, we instead get the following:

```
Iteration	Posterior	Likelihood	Prior	branch_rates_morpho	extinction_rate	origin_time	psi[1]	psi[2]	psi[3]	psi[4]	psi[5]	speciation_rate
0	-7460.669	-7224.135	-236.5342	0.04483802	0.0352606	3.150825	8.13918	6.77304	12.8996	6.34757	0.762531	0.07298359
5	-3173.365	-3110.715	-62.64938	0.1090368	0.6788802	2.024353	3.00599	0.20766	2.05864	0.198251	3.43668	1.290087
10	-3173.946	-3109.182	-64.76376	0.106626	0.6785263	2.025254	7.59532	0.608569	3.07613	0.191491	3.08322	0.9171527
```

And under Ubuntu 24.04, GCC 11 + MPI, this:

```
Iteration	Posterior	Likelihood	Prior	branch_rates_morpho	extinction_rate	origin_time	psi[1]	psi[2]	psi[3]	psi[4]	psi[5]	speciation_rate
0	-8091.393	-7854.859	-236.5342	0.04483802	0.0352606	3.150825	8.13918	6.77304	12.8996	6.34757	0.762531	0.07298359
5	-3152.836	-3085.698	-67.13858	0.1170385	1.968243	2.007533	1.80077	0.556789	2.8552	0.311812	4.55351	2.069847
10	-3124.702	-3062.263	-62.43925	0.1135802	0.353259	2.057422	6.40239	0.23673	4.08645	0.00376771	4.89217	1.803472
```

**To reproduce**
Un-disable the [skyline FBD test](https://github.com/revbayes/revbayes/blob/development/tests/test_FBD/scripts/FBD_one_parameter_skyline.Rev.broken) recently added to the development branch by renaming it from `FBD_one_parameter_skyline.Rev.broken` to `FBD_one_parameter_skyline.Rev`, and by adding the `.log` and `.errout` files from [this zipped directory](https://github.com/user-attachments/files/22686272/FBD_skyline_output_expected.zip) to the [`output_expected`](https://github.com/revbayes/revbayes/tree/development/tests/test_FBD/output_expected) folder.

**Expected behavior**
The output of the analysis should be identical regardless of the compiler used.

**Computer info**
See above regarding OS info. The GitHub Actions results reported above were obtained for RevBayes v1.4.0-preview, development branch, commit 0eb4184.

### LINKED ISSUE #887: [BUG] FBD analysis hanging after burnin completion when `nruns` > 1
**Describe the bug**
I'm trying to conduct a fairly large and complex FBD analysis (151 taxa, 270 characters, skyline rates with 2 independent timelines for different FBD rate parameters, white-noise relaxed clock), and while performing a single run is unproblematic, the analysis always hangs with multiple runs.

To investigate why this might be the case, I prepared a test version of my original script that only specified 20 iterations of burnin followed by 20 iterations of sampling. I then wrote a bash script to run this script 100 times. With the single-thread version and `nruns=1`, the results were encouraging:

- 99 successful completions
- 1 failure to find a starting state with computable probability

Next up, I switched to the MPI version, specified `nruns=2` in the Rev script, and `mpirun -np 2` in the bash script. I also placed a time limit on the execution of each attempt:

```sh
#!/bin/bash

for i in {1..100}
do
  timeout 400 mpirun -np 2 ./build-mpi/rb-mpi -i ~/Downloads/FBD_multiple_timelines/FBD_multiple_timelines_relaxed_clock.Rev
done

```

The results were much worse:

- 4 successful completions
- 1 failure to find a starting state with computable probability
- 1 timeout while re-drawing initial states
- 94 timeouts between the completion of the burnin stage and the beginning of the sampling stage

I also wanted to see if the number of processes and/or runs has any effect, so I re-ran everything one more time with `nruns=6` and `mpirun -np 6`. This did make things even worse:

- no successful completions at all
- no failures to find a starting state with computable probability
- 3 timeouts while re-drawing initial states
- 97 timeouts between the completion of the burnin stage and the beginning of the sampling stage

Finally, to determine whether it's the number of processes that matters (i.e., whether the problem is specific to the MPI version) or the number of runs, I re-ran everything one more time with `nruns=2` but using the single-threaded version of RevBayes, yielding the following results:

- 5 successful completions
- no failures to find a starting state with computable probability
- 95 timeouts after completing less than 5% of the burnin stage

While the success rate is comparable when using the MPI and single-threaded versions of the program, and both versions appear to suffer from the same fundamental problem, the point at which they hang is different, and this difference is too consistent to be stochastic. Moreover, it's strange that the single-threaded version always ends up hanging after completing the same fraction of the burnin stage, despite the fact that each of the 100 attempts uses a different random seed.

The other notable difference between the two setups was the number of times that the warning `Attempting to set new age of taxon <x> incompatible with age range` (inserted into `TopologyNode::setAge()` by PR #559) was printed to the screen. We might expect more runs to emit more warnings, but the number of warnings clearly rises much faster than the number of runs:

- 1 run, 1 process: 4 times
- 2 runs, 2 processes: 186 times
- 6 runs, 6 processes: 1,094 times
- 2 runs, 1 process: 264 times

I'll try re-running the analyses under `debugMCMC=1` to see if that sheds any light on what the issue might be.

**To reproduce**
[This zipped directory](https://github.com/user-attachments/files/23453538/FBD_multiple_timelines.zip) contains the following files:

- `ages.tsv`: anonymized taxon age data needed to run the analysis
- `chars.nex`: anonymized character data needed to run the analysis
- `FBD_multiple_timelines_relaxed_clock.Rev`: Rev script specifying the analyses. One absolute path and the `nruns` argument of the `mcmc()` function may have to be changed.
- `test_output_1_process_1_run.txt`: stdout + stderr from 100 attempts under the settings described
- `test_output_1_process_2_runs.txt`: as above
- `test_output_2_processes_2_runs.txt`: as above
- `test_output_6_processes_6_runs.txt`: as above

**Expected behavior**
The analysis should proceed to the sampling stage even when multiple runs are specified.

**Computer info**
macOS 26.0.1 (Tahoe), ARM64 architecture, RevBayes 1.4.0-preview, commit 7ffcff8.

**Additional context**
The analysis seemingly hangs early on during the burnin stage when two runs share the same process, but only after burnin completion if each run is given a process of its own. However, as @hoehna pointed out to me, these may be two different manifestations of the same issue. Perhaps what's happening is that with the MPI version, whatever causes the analysis to hang always happens on the non-active process (i.e., the one that doesn't get to print its status to the screen). Then, when the time comes for `MonteCarloAnalysis::burnin()` to synchronize the processes:

https://github.com/revbayes/revbayes/blob/cbe72b0372cf2c869d951293b383181bacdb9e99/src/core/analysis/MonteCarloAnalysis.cpp#L240-L251

it's unable to do so, because one of them is still hanging. The question is then why the issue would always happen on the non-active process, instead of occurring with the same probability on either the active process or the non-active process. @hoehna thinks that when we clone the model to spin up additional processes, we might be performing a shallow copy of some pointer variables that actually require a deep copy.

### PR DESCRIPTION
**Pull request by davidcerny**
Fixes #887. The only solution I was able to find was to always recompute the `node_index` in the `doProposal()` function. I also tried implementing a two-step approach where a copy constructor first marks the `node_index` for recomputation, and then `prepareProposal()` or `doProposal()` only recompute it when it is marked as such. This failed to solve the problem. The lookup that needs to happen every time the proposal is performed is going to slow things down, but hopefully not too much. If need be, I can try to benchmark it.

### CODE REVIEW

**Comment by davidcerny** [comment]
It looks like this is another one of those tests that's extremely sensitive to the compiler used, just like the skyline FBD one I tried to add in PR #845. See issue #858. In this case, too, the output is completely different starting from generation 0 – it's not like the sampled parameter values just differ in the $n$-th decimal place:

Ubuntu 22.04, GCC 10:

```
0	-2206.623	-2448.962	242.3392	1	0.000941988	0.00269374	0.000739394	0.000805488	0.00194853	0.000867063	0.00102343	0.000640193	0.00032503	0.000851253	0.00127665	0.00108601	0.00119809	0.000644953	0.000822798	0.000442464	0.00127489	0.00159845	0.00156627	0.000240128	0.000673678	0.00131596	0.000802754	0.000271846	0.00145136	0.00147131	0.00189308	0.000818109	0.000421953	0.000475766	0.000998674	0.000742649	0.000769676	0.00109625	0.000603476	0.000573901	0.000812451	0.00122888	0.00084913	0.000720732	0.00138762	0.00168311	0.00095269	0.000166898	7.76111e-11	2.92399e-08	0.00445321	0.000813087	4.16905e-105	0.0050554	2.5049e-08	1.98626e-14	3.1711e-17	8.00004e-05	0.000719762	4.74704e-10	2.43703e-58	1.22385e-13	0.000808973	5.08764e-06	0.00173691	1.04238e-10	0.000675856	4.86948e-07	0.00146733	0.00199238	8.34824e-05	0.00106761	0.000405439	0.00105435	1.44004e-126	6.34607e-05	0.000322991	0.000123886	0.00143136	0.00149366	0.00126663	0.00108083	0.0013504	0.000767754	0.00144335	0.000437374	0.00131214	0.00098527	0.136954	0.476752	1	2.38629	0.04089133	0.02292314	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.2501437	33.5483	4.26911	4.80923	8.65424	2.06008	8.60734	7.35407	7.35407	1.8715	12.1397	4.24203	4.21111	4.21111	4.18273	4.18273	4.31213	4.30276	4.30276	4.43309	4.28145	4.28145	7.97579	12.1549	7.99819	7.90669	12.0858	7.91434	2.0837	2.03564	2.03564	5.38012	3.38254	7.55544	7.47474	4.59905	7.40797	8.49897	16.8231	8.25932	16.8287	16.8287	9.03971	2.93669	0.769963	0.0326628	0.0667698	0.299362	0.54389	0.00765624	0.083849	0.162093	0.184492	0.0646443	0.200757	0.00936975	0.0199193	0.0291371	0.000750982	0.0301618	0.0900226	0.101036	0.0491177	7.65746	0.264392	1.52525	0.212204	0.495822	4.65038	0.400272	3.98768	0.016153	0.185219	0.218663	0.724867	7.43897	8.24842	0.742945	13.6383	6.17434	1.72993	2.50368	1.87254	7.20155	33.2528	0.001038213	0	223.5693	0.007646904	0.907317	2.5946	0.71218	0.77584	1.87681	0.83515	0.985765	0.61663	0.313067	0.819922	1.22966	1.04604	1.15399	0.621214	0.792513	0.426178	1.22796	1.53961	1.50862	0.23129	0.648883	1.26753	0.773208	0.26184	1.39794	1.41716	1.8234	0.787997	0.406422	0.458255	0.961917	0.715315	0.741346	1.0559	0.581264	0.552778	0.782548	1.18365	0.817877	0.694205	1.33655	1.62116	0.917625	0.160755	7.47545e-08	2.81636e-05	4.2893	0.78316	4.0156e-102	4.86933	2.4127e-05	1.91315e-11	3.05438e-14	0.0770559	0.69327	4.57231e-07	2.34733e-55	1.1788e-10	0.779197	0.00490038	1.67298	1.00402e-07	0.65098	0.000469026	1.41332	1.91905	0.0804097	1.02831	0.390516	1.01555	1.38704e-123	0.0611249	0.311103	0.119326	1.37868	1.43869	1.22001	1.04104	1.3007	0.739495	1.39022	0.421275	1.26385	0.949006	0.001515412	0.06381447	66	72.1	100.5	72.1	72.1	174.1	157	66	145	89.8	89.8	152.1	86.3	168.3	100.5	100.5	89.8	89.8	66	100.5	66	66	157	83.6	132.9	72.1	89.8	66	66	66	66	66	66	66	66	93.9	89.8	113	83.6	83.6	66	83.6	89.8	0.3592154
5	-1370.881	-1645.259	274.378	0.5235013	0.031483	0.0838276	0.0303328	0.0222072	0.0602146	0.0340435	0.0296471	0.0234686	0.00895862	0.0307216	0.0342815	0.0362965	0.0389024	0.0220905	0.0251658	0.014788	0.0426091	0.0524998	0.0407133	0.00578849	0.0378311	0.0405096	0.0268295	0.0108095	0.0405899	0.050274	0.0533829	0.0281449	0.0141024	0.0174084	0.0281094	0.038268	0.0384054	0.0243772	0.0256671	0.0219223	0.0240881	0.038924	0.0322999	0.0185778	0.0500792	0.0529711	0.0462736	0.0057661	2.98851e-09	1.02811e-06	0.161482	0.0249101	1.46025e-103	0.194755	7.00702e-07	7.1352e-13	1.10906e-15	0.00215612	0.0314528	2.01527e-08	8.41363e-57	3.47457e-12	0.0310165	0.000248884	0.0486726	3.65568e-09	0.0223596	1.59185e-05	0.0442535	0.0648182	0.00294446	0.0356814	0.00984318	0.0352385	3.27204e-125	0.00212097	0.010819	0.00384926	0.0428298	0.045428	0.029878	0.0313773	0.0441382	0.0233525	0.0547026	0.0171255	0.0451738	0.0317499	0.037822	0.266981	0.836643	2.85855	0.04389007	0.0511674	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.4364732	27.5991	3.51206	3.9564	7.11956	1.69476	7.08098	6.04996	6.04996	1.53962	9.98691	3.48978	3.46435	3.46435	3.441	3.441	3.54745	3.53974	3.53974	3.64696	3.52221	3.52221	6.56143	9.99946	6.57986	6.50458	9.94261	6.51088	1.7142	1.67465	1.67465	4.42606	2.78271	6.21562	6.14923	3.78349	6.0943	6.99183	13.8398	6.79468	13.8445	13.8445	7.43668	2.41592	0.633424	0.0268707	0.0549294	0.246275	0.447441	0.00629854	0.0689799	0.133349	0.151775	0.0531808	0.165156	0.00770819	0.016387	0.0239702	0.000617809	0.0248132	0.0740587	0.083119	0.0404076	6.29955	0.217507	1.25478	0.174573	0.407897	3.82571	0.329291	3.28054	0.0132885	0.152374	0.179887	0.596325	6.1198	6.78571	0.611197	11.2198	5.07943	1.42316	2.0597	1.54048	5.92448	27.356	0.03469898	1	223.6296	0.03963111	0.907317	2.41585	0.874171	0.639996	1.73534	0.98111	0.854407	0.676348	0.258181	0.885375	0.987968	1.04604	1.12114	0.636632	0.725261	0.426178	1.22796	1.51301	1.17333	0.16682	1.09026	1.16746	0.773208	0.311522	1.16977	1.44886	1.53846	0.811115	0.406422	0.501699	0.810094	1.10286	1.10682	0.702533	0.739709	0.631785	0.694202	1.12176	0.93086	0.535399	1.44325	1.52659	1.33357	0.166175	8.61267e-08	2.96294e-05	4.65379	0.717891	4.20834e-102	5.6127	2.01937e-05	2.05631e-11	3.19624e-14	0.0621378	0.906446	5.80786e-07	2.42475e-55	1.00135e-10	0.893874	0.00717265	1.40271	1.05354e-07	0.644388	0.00045876	1.27535	1.86801	0.0848571	1.02831	0.283673	1.01555	9.4298e-124	0.0611249	0.311795	0.110933	1.23432	1.3092	0.861063	0.904273	1.27203	0.673004	1.57649	0.493545	1.30188	0.915011	0.06156537	0.09505747	66	72.6042	100.5	73.466	72.8671	174.119	157.642	66	145.53	90.2349	89.8238	152.824	86.4255	168.372	101.102	100.667	90.8964	90.6126	66	100.732	66	66	157.674	83.9381	133.77	72.434	90.4138	66	66	66	66	66	66	66	66	93.9595	90.1932	113.693	83.7135	83.9941	66	83.6325	89.9406	0.5382786
```

Ubuntu 22.04, GCC 12:

```
0	-2179.637	-2305.844	126.2067	1	0.00133668	0.00274053	0.000596727	0.000963094	0.000557312	0.00114163	0.00101527	0.00104373	0.00225863	0.00132217	0.00121539	0.000929078	0.0007678	0.00205029	0.000732142	0.000425698	0.00318081	0.00315045	0.00238567	0.000667299	0.00320802	0.000777562	0.000451399	0.000373702	0.00293982	0.00182806	0.0019627	0.00466834	0.00131503	0.00165231	0.0012735	0.00259654	0.00137156	0.00053331	0.0012897	0.0023734	0.00111987	0.000955959	0.00226356	0.00132642	0.00213101	0.00255002	0.00171827	0.000169153	1.41916e-18	5.24258e-27	1.35828e-08	0.00998643	0.000629129	5.11946e-06	0.00661714	1.75343e-10	5.41609e-23	2.36986e-79	9.29835e-07	0.0201984	0.0104057	0.00175125	8.34531e-75	1.85869e-69	3.69382e-06	0.00333483	0.00986831	0.00188496	3.46221e-05	4.17156e-06	8.34824e-08	0.0023077	1.62205e-06	0.000264192	3.74358e-27	1.39068e-26	0.00101172	5.12764e-05	0.00521443	0.00174977	3.34932e-05	0.00130835	0.00197634	0.00117526	0.00166874	0.000308962	0.00140377	0.00169593	0.136954	0.476752	1	2.38629	0.007014646	0.009347597	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.2433663	12.4385	1.58284	1.78309	3.20869	0.763805	3.1913	2.72663	2.72663	0.693887	4.59899	2.93152	2.93152	2.95714	2.93436	1.55081	1.55081	1.56161	1.56161	1.57279	1.57279	1.59879	1.60617	1.56133	1.56133	1.66184	4.50096	4.51492	0.772564	0.754742	0.754742	1.99476	1.25413	2.80129	2.77137	1.70517	2.74662	3.15112	6.23741	3.06226	6.23951	6.23951	3.3516	1.08882	0.285475	0.0121102	0.0247559	0.110993	0.201655	0.0448386	0.0374606	0.0225179	0.0257983	0.0366013	0.00790245	0.00347397	0.0448459	0.0182111	2.82199	0.0171273	0.00565636	0.00830459	0.0600984	0.0940253	0.0239678	0.56551	0.0786778	0.183833	1.7242	0.148407	1.47849	0.00598896	0.0686728	0.0810727	0.268755	2.75811	3.05822	0.275458	5.05661	2.28923	0.641397	0.928277	0.694271	2.67008	12.3289	0.001364427	0	219.7903	0.003006594	0.979662	2.00855	0.437346	0.705859	0.408458	0.836712	0.744101	0.764961	1.65537	0.969032	0.890769	0.680929	0.562727	1.50268	0.536593	0.311998	2.33124	2.30899	1.74847	0.489069	2.35119	0.569882	0.330834	0.273889	2.15462	1.3398	1.43848	3.42147	0.963798	1.21099	0.933357	1.90302	1.00522	0.390867	0.945233	1.73949	0.82076	0.70063	1.65898	0.972142	1.56183	1.86893	1.25933	0.123973	1.04011e-15	3.84233e-24	9.95495e-06	7.31913	0.461094	0.00375209	4.84975	1.2851e-07	3.9695e-20	1.73689e-76	0.000681484	14.8036	7.62645	1.28351	6.11634e-72	1.36225e-66	0.00270723	2.44412	7.23257	1.3815	0.0253748	0.00305737	6.11849e-05	1.69133	0.00118882	0.193628	2.7437e-24	1.01924e-23	0.741501	0.0375809	3.8217	1.28242	0.0245474	0.958903	1.44848	0.861361	1.22304	0.226441	1.02884	1.24296	0.005371509	0.01636224	66	72.1	100.5	72.1	72.1	174.1	157	66	145	89.8	89.8	152.1	86.3	168.3	100.5	100.5	89.8	89.8	66	100.5	66	66	157	83.6	132.9	72.1	89.8	66	66	66	66	66	66	66	66	93.9	89.8	113	83.6	83.6	66	83.6	89.8	0.5712907
5	-1427.902	-1655.868	227.9655	1.426202	0.01956	0.0565862	0.0106678	0.0159669	0.0114502	0.0128637	0.0165094	0.0169722	0.0392994	0.0183235	0.0241905	0.0170137	0.0141192	0.0283928	0.0136954	0.0069223	0.0432792	0.0370273	0.0412641	0.0137227	0.0521658	0.0156596	0.00734022	0.00637299	0.0364137	0.0297261	0.0351517	0.0645097	0.0218416	0.0263645	0.0240422	0.050407	0.0245965	0.00908343	0.0229467	0.038594	0.017841	0.0186924	0.0368079	0.0228288	0.0332047	0.0414659	0.0275773	0.00234401	2.8077e-17	8.77443e-26	2.00197e-07	0.130871	0.0136158	0.000125312	0.088693	3.50132e-09	5.54866e-22	3.63724e-78	1.51201e-05	0.328447	0.169208	0.0258135	1.20095e-73	3.67569e-68	5.03133e-05	0.0542279	0.178301	0.0297165	0.000573476	5.5184e-05	1.50346e-06	0.0375257	2.80884e-05	0.00520254	6.86152e-26	1.91832e-25	0.0185813	0.000769388	0.0847865	0.027966	0.000448577	0.0221674	0.0260853	0.0236911	0.0309946	0.00522829	0.0279863	0.0265419	0.213694	0.575793	1.04578	2.16474	0.007128134	0.05256307	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.2902791	18.6607	2.37463	2.67506	4.81379	1.14589	4.7877	4.09059	4.09059	1.04099	6.89956	4.39797	4.39797	4.43641	4.40223	2.32658	2.32658	2.34278	2.34278	2.35956	2.35956	2.39856	2.40964	2.34237	2.34237	2.49316	6.7525	6.77344	1.15903	1.13229	1.13229	2.99261	1.88148	4.2026	4.15771	2.55815	4.12057	4.72742	9.35759	4.59412	9.36073	9.36073	5.0282	1.63349	0.42828	0.0181682	0.0371397	0.166515	0.302531	0.0672684	0.0561997	0.0337821	0.0387036	0.0549106	0.0118555	0.00521178	0.0672795	0.027321	4.23365	0.025695	0.00848587	0.0124588	0.0901618	0.14106	0.0359574	0.848398	0.118035	0.275793	2.5867	0.222645	2.21809	0.00898485	0.103025	0.121628	0.403196	4.13781	4.58806	0.413252	7.58611	3.43438	0.962247	1.39263	1.04157	4.00575	18.4963	0.02218702	2	219.9775	0.02149853	0.881596	2.55042	0.480812	0.719651	0.516077	0.579784	0.744101	0.764961	1.77128	0.825867	1.0903	0.76683	0.636372	1.2797	0.617272	0.311998	1.95066	1.66887	1.85983	0.618502	2.35119	0.705799	0.330834	0.287239	1.64121	1.3398	1.58433	2.90754	0.984432	1.18828	1.08362	2.27191	1.1086	0.409403	1.03424	1.73949	0.804118	0.842493	1.65898	1.02893	1.49658	1.86893	1.24295	0.105648	1.26547e-15	3.95476e-24	9.02315e-06	5.89853	0.613685	0.00564798	3.99752	1.5781e-07	2.50086e-20	1.63935e-76	0.000681484	14.8036	7.62645	1.16345	5.41286e-72	1.65668e-66	0.00226769	2.44412	8.03628	1.33936	0.0258473	0.00248722	6.7763e-05	1.69133	0.00126598	0.234486	3.09258e-24	8.64613e-24	0.837483	0.0346774	3.82144	1.26046	0.020218	0.999116	1.1757	1.06779	1.39697	0.235646	1.26138	1.19628	0.05822178	0.05969121	66	72.1773	100.991	72.4232	72.6109	174.854	157.401	66	145.024	90.183	89.9386	152.134	86.5412	169.312	101.476	101.58	90.7784	89.9509	66	100.506	66	66	157.407	83.7405	133.416	73.2164	91.7712	66	66	66	66	66	66	66	66	95.4129	90.5506	113.131	84.0904	84.0026	66	83.7478	90.9692	0.8805832
```

Latest Ubuntu, GCC 13:

```
0	-3000.635	-2624.481	-376.1542	1	0.000497325	0.000453664	0.000418771	0.000490689	0.000489431	0.000411733	0.000464451	0.000381825	0.000444378	0.000460364	0.000439411	0.000532694	0.000470534	0.000494863	0.000426634	0.000428346	0.000436728	0.000412898	0.000477133	0.000555164	0.000540714	0.000459355	0.000642462	0.000320029	0.000455652	0.000476544	0.00053825	0.00044978	0.000427463	0.000496581	0.00049425	0.00050948	0.000408368	0.000511398	0.000387093	0.000403211	0.000470083	0.000486369	0.000335521	0.000439931	0.000397844	0.00047314	0.000487019	0.000425903	0.000444257	2.23435e-08	1.25489e-05	0.000690324	0.000521271	6.79064e-05	0.000425951	0.0043555	2.77599e-05	3.90784e-05	3.61811e-39	2.23526e-05	0.00211976	0.000297271	0.00033977	0.000450159	0.000468117	0.000381799	0.000164048	8.3748e-05	0.000664645	0.000441941	0.000849804	0.000325595	0.000552613	0.000802655	0.000945423	0.000311766	0.000393502	0.000542835	1.44166e-12	0.000578057	0.000348839	0.000459574	0.000419003	0.000539947	0.000403911	0.00034737	0.000409818	0.000469004	0.136954	0.476752	1	2.38629	0.175275	0.1725794	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.4188804	26.009	80.061	149.285	149.285	66.9154	65.132	51.1946	26.4127	18.4545	18.0288	18.0288	16.5751	107.516	37.5699	37.2961	37.2961	37.0447	37.0447	38.1908	38.1078	38.1078	39.262	37.919	37.919	107.651	70.6383	70.8367	107.039	70.0263	70.0941	65.6094	41.3233	65.275	65.275	68.852	76.2317	73.1494	149.045	18.2453	76.647	42.5933	37.8098	297.123	3.57702	6.41985	0.0678082	0.742616	1.43559	1.63397	0.572528	1.77802	0.082984	0.176417	0.258055	0.00665114	0.267131	0.797293	0.894834	0.435016	67.819	2.34161	13.5085	6.27069	0.425722	4.39129	41.1865	3.54505	35.1742	0.477408	0.591353	0.714711	8.35646	65.8839	72.7636	0.0499951	6.81924	6.57996	120.789	54.6836	15.3213	22.1741	16.5843	63.7811	294.506	0.0004596122	0	200.8519	0.124398	1.08205	0.987058	0.911139	1.06761	1.06488	0.895826	1.01053	0.830755	0.966854	1.00163	0.956047	1.15901	1.02376	1.0767	0.928248	0.931973	0.950211	0.898361	1.03812	1.2079	1.17646	0.999441	1.39784	0.696303	0.991384	1.03684	1.1711	0.978607	0.930052	1.08043	1.07536	1.1085	0.888506	1.11267	0.842216	0.877284	1.02278	1.05822	0.730009	0.957179	0.865608	1.02943	1.05963	0.926658	0.966591	4.86137e-05	0.0273032	1.50197	1.13415	0.147747	0.926761	9.47646	0.0603985	0.0850247	7.87208e-36	0.0486336	4.61207	0.646788	0.739254	0.979433	1.0185	0.830698	0.356928	0.182215	1.4461	0.961552	1.84896	0.708413	1.20235	1.74638	2.057	0.678323	0.856161	1.18107	3.13669e-09	1.25771	0.758986	0.999917	0.911645	1.17479	0.878809	0.755789	0.891661	1.02044	7.574769e-05	0.3478544	66	72.1	100.5	72.1	72.1	174.1	157	66	145	89.8	89.8	152.1	86.3	168.3	100.5	100.5	89.8	89.8	66	100.5	66	66	157	83.6	132.9	72.1	89.8	66	66	66	66	66	66	66	66	93.9	89.8	113	83.6	83.6	66	83.6	89.8	0.4961255
5	-1955.783	-1673.06	-282.7227	0.6622681	0.0166529	0.0133928	0.0139135	0.0175678	0.0152692	0.014741	0.0166284	0.0180345	0.0159097	0.0158319	0.0157319	0.0190717	0.0176263	0.0194372	0.0152745	0.0217927	0.0209016	0.0147827	0.0170824	0.0178315	0.0172505	0.016446	0.0209957	0.0132949	0.0163546	0.0170174	0.0185293	0.0161031	0.0168614	0.0175166	0.014584	0.0134107	0.0173643	0.0183092	0.0139535	0.0152759	0.01683	0.0184083	0.0148313	0.0175425	0.0152329	0.0169395	0.0155884	0.0155309	0.0163028	7.30384e-07	0.000386495	0.0171255	0.0141044	0.00148213	0.0178363	0.147149	0.000922052	0.00111071	1.08433e-37	0.000800273	0.0575076	0.010643	0.0128693	0.0161167	0.018229	0.0163903	0.0058733	0.00313038	0.018156	0.015243	0.0293403	0.011657	0.0237246	0.0418288	0.0264076	0.00992613	0.0140883	0.0197274	5.08584e-11	0.0153006	0.0144873	0.0164538	0.0147751	0.0214741	0.015866	0.0124366	0.0172427	0.0167914	0.0661542	0.34517	0.910041	2.67863	0.100884	0.1522375	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.1588849	28.8351	88.7601	165.505	165.505	74.1862	72.209	56.7572	29.2826	20.4597	19.9877	19.9877	18.3761	119.198	41.6521	41.3486	41.3486	41.0699	41.0699	42.3404	42.2484	42.2484	43.5281	42.0392	42.0392	119.348	78.3136	78.5336	118.67	77.6351	77.7103	72.7383	45.8133	72.3676	72.3676	76.3333	84.5148	81.0976	165.24	20.2277	84.9752	47.2214	41.9181	329.408	3.96569	7.1174	0.075176	0.823306	1.59158	1.81151	0.634737	1.97121	0.0920008	0.195586	0.286095	0.00737383	0.296156	0.883924	0.992063	0.482283	75.188	2.59604	14.9763	6.95205	0.47198	4.86843	45.6616	3.93024	38.9961	0.529282	0.655607	0.792369	9.26444	73.0426	80.6699	0.0554274	7.5602	7.29491	133.914	60.6254	16.986	24.5834	18.3863	70.7114	326.506	0.01645515	5	201.2256	0.02875735	1.01202	0.813895	0.845539	1.06761	0.927931	0.895826	1.01053	1.09598	0.966854	0.962125	0.956047	1.15901	1.07117	1.18123	0.928248	1.32437	1.27022	0.898361	1.03812	1.08364	1.04834	0.999441	1.27593	0.807945	0.993891	1.03417	1.12605	0.978607	1.02469	1.06451	0.88629	0.814985	1.05525	1.11267	0.84797	0.928333	1.02278	1.1187	0.901319	1.06608	0.925724	1.02943	0.947326	0.943831	0.990744	4.43863e-05	0.0234878	1.04074	0.857145	0.0900709	1.08393	8.94241	0.0560342	0.0674994	6.58959e-36	0.0486336	3.49481	0.646788	0.782082	0.979433	1.1078	0.996062	0.356928	0.190237	1.10337	0.926337	1.78305	0.708413	1.44177	2.54199	1.60482	0.603223	0.856161	1.19886	3.09073e-09	0.929836	0.880409	0.999917	0.897903	1.30501	0.964197	0.755789	1.04786	1.02044	0.002446148	0.2531215	66	72.2425	100.812	72.5716	72.5516	175.174	157.35	66	145.239	91.5134	90.3258	152.167	86.306	168.659	100.822	100.828	90.0583	90.4041	66	101.188	66	66	157.459	83.7107	133.271	72.6018	90.2932	66	66	66	66	66	66	66	66	94.2399	89.8921	113.556	83.6135	83.6548	66	83.852	90.3907	0.6014405
```

Latest Ubuntu, GCC 14:

```
0	-6077.932	-2414.433	-3663.499	1	0.000846958	0.00106854	0.000997991	0.00102023	0.000973665	0.00110289	0.00105678	0.000746304	0.000782374	0.00111334	0.000892503	0.00115512	0.000845407	0.00124012	0.00070884	0.000662143	0.00128124	0.000956291	0.00125646	0.00124241	0.000869011	0.000678589	0.000592055	0.00096566	0.000935688	0.00112441	0.000966469	0.00075727	0.00108749	0.000939101	0.000637946	0.000800514	0.00136862	0.00110182	0.00091193	0.000539031	0.00110706	0.000924422	0.00097407	0.00116219	0.00111394	0.00106218	0.000698687	7.0538e-05	4.01976e-07	0.00019048	0.00161062	2.93845e-08	0.000927113	0.00222173	2.27551e-05	0.000314853	1.91124e-11	0.000176675	1.83231e-11	0.00108336	1.05455e-05	0.000234098	0.000876603	0.00077592	0.00226315	1.62306e-05	0.00131858	0.00123008	0.000294054	0.000587204	0.000295228	0.000760274	1.12864e-08	0.00155881	0.00106833	0.00185705	0.000816529	0.000925951	5.80827e-12	0.00148207	0.00249142	0.000976727	0.000524989	0.000513743	0.000797383	0.000281387	0.000640749	0.00128355	0.136954	0.476752	1	2.38629	0.3474292	0.3644621	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.9335518	85.8717	10.9274	22.1518	5.27307	23.1385	43.1448	43.1448	43.0612	22.0318	12.1494	18.8238	18.8238	18.9618	19.1327	18.8652	18.8652	5.33355	5.21051	5.21051	31.75	20.2579	11.0135	10.779	10.7063	10.7063	10.8581	10.8581	11.0375	11.0885	10.7809	10.7809	11.4729	31.0732	20.4152	20.2383	20.2383	31.1696	4.79038	13.7712	8.6581	21.1554	7.51688	12.3099	0.176889	0.0573323	0.414901	0.30763	0.258616	0.1009	0.0726584	0.180026	0.0545561	0.0239832	0.309603	0.125724	19.4821	0.118242	0.511283	0.165467	3.90411	1.8123	0.123038	1.26913	11.9033	1.02456	11.2409	1.0338	1.8554	0.137976	0.170907	0.206559	2.4151	19.0411	21.0294	0.0144491	1.97083	1.90168	34.9093	15.8041	4.42801	6.40854	4.79304	18.4334	85.1153	0.0009886458	0	201.2592	5.120446	0.856685	1.08081	1.00945	1.03194	0.984847	1.11555	1.06892	0.754875	0.791359	1.12613	0.902753	1.16839	0.855116	1.25436	0.716981	0.669747	1.29595	0.967273	1.27089	1.25667	0.878991	0.686383	0.598854	0.97675	0.946434	1.13733	0.977568	0.765967	1.09997	0.949886	0.645273	0.809708	1.38434	1.11447	0.922403	0.545222	1.11978	0.935038	0.985257	1.17554	1.12673	1.07438	0.706711	0.0713481	0.000406593	0.192668	1.62911	2.9722e-05	0.93776	2.24725	0.0230164	0.318469	1.93319e-08	0.178704	1.85335e-08	1.0958	0.0106666	0.236787	0.88667	0.784831	2.28914	0.016417	1.33372	1.2442	0.297431	0.593947	0.298619	0.769005	1.1416e-05	1.57672	1.0806	1.87838	0.825907	0.936585	5.87497e-09	1.49909	2.52003	0.987945	0.531018	0.519643	0.806541	0.284618	0.648108	1.29829	0.0005637741	0.7118913	66	72.1	100.5	72.1	72.1	174.1	157	66	145	89.8	89.8	152.1	86.3	168.3	100.5	100.5	89.8	89.8	66	100.5	66	66	157	83.6	132.9	72.1	89.8	66	66	66	66	66	66	66	66	93.9	89.8	113	83.6	83.6	66	83.6	89.8	0.5119631
5	-2047.977	-1649.217	-398.7593	1.497183	0.0344317	0.0389418	0.0480501	0.0416182	0.0467331	0.0431261	0.0373597	0.0253913	0.0285015	0.04829	0.038588	0.0435684	0.0344868	0.0426219	0.0305808	0.0312178	0.0491743	0.0389525	0.0608412	0.0402816	0.0288737	0.0228795	0.0247397	0.0368391	0.048407	0.042885	0.0492094	0.025814	0.0778863	0.0369145	0.036305	0.0310625	0.0513363	0.050751	0.0360296	0.0214859	0.0451606	0.0388606	0.0425373	0.0370701	0.0386622	0.0390765	0.0285016	0.00172608	1.45714e-05	0.00629153	0.0485264	1.24854e-06	0.024013	0.087401	0.00118248	0.0129965	1.03984e-09	0.00542864	8.54216e-10	0.0441935	0.000430182	0.00764691	0.040689	0.0386728	0.0923209	0.000645697	0.0425399	0.0501787	0.00966882	0.0244929	0.00980934	0.0287446	5.86309e-07	0.0635889	0.0325932	0.0578751	0.0382689	0.0377725	2.38674e-10	0.0510316	0.0781956	0.0397787	0.0213996	0.0217195	0.0302287	0.00968292	0.023238	0.0453446	0.224887	0.588087	1.05026	2.13677	0.1653509	0.1040851	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.3254978	81.0263	10.3108	20.9018	4.97553	21.8328	40.7103	40.7103	40.6314	20.7886	11.4639	17.7616	17.7616	17.8918	18.0531	17.8007	17.8007	5.03259	4.9165	4.9165	29.9584	19.1148	10.3921	10.1707	10.1022	10.1022	10.2454	10.2454	10.4147	10.4628	10.1726	10.1726	10.8255	29.3199	19.2632	19.0963	19.0963	29.4108	4.52008	12.9942	8.16955	19.9617	7.09273	11.6153	0.166907	0.0540973	0.391489	0.290271	0.244023	0.0952068	0.0685586	0.169868	0.0514777	0.0226299	0.292133	0.11863	18.3828	0.11157	0.482433	0.15613	3.68381	1.71003	0.116096	1.19752	11.2317	0.966744	10.6066	0.975464	1.75071	0.13019	0.161263	0.194904	2.27883	17.9667	19.8428	0.0136338	1.85962	1.79437	32.9395	14.9124	4.17815	6.04693	4.52258	17.3933	80.3125	0.04032997	2	201.7006	0.05022884	0.85375	0.96558	1.19142	1.03194	1.15877	1.06933	0.92635	0.62959	0.706709	1.19737	0.956806	1.0803	0.855116	1.05683	0.758266	0.774061	1.2193	0.965846	1.50858	0.998801	0.715937	0.567309	0.613433	0.913443	1.20027	1.06335	1.22017	0.640071	1.93123	0.915313	0.9002	0.770208	1.27291	1.25839	0.893369	0.532752	1.11978	0.963566	1.05473	0.919169	0.958647	0.96892	0.706711	0.0427989	0.000361304	0.156001	1.20324	3.09581e-05	0.595414	2.16715	0.0293202	0.322255	2.57833e-08	0.134606	2.11807e-08	1.0958	0.0106666	0.189609	1.0089	0.958909	2.28914	0.0160104	1.0548	1.2442	0.239743	0.607313	0.243227	0.712736	1.45378e-05	1.57672	0.808164	1.43504	0.948895	0.936585	5.91803e-09	1.26535	1.9389	0.98633	0.530612	0.538544	0.749534	0.240092	0.576196	1.12434	0.02437343	0.2694359	66	72.3138	100.5	73.045	72.8166	174.282	157.583	66	146.145	90.2507	90.6826	152.225	86.6185	169.022	100.678	101.599	90.995	90.3351	66	102.223	66	66	157.536	84.2359	133.751	73.1367	90.0042	66	66	67.0605	66.7146	66	67.147	67.29	66	93.9532	90.4446	114.165	83.6097	84.9421	66	83.6336	90.5686	0.3863073
```

Latest Ubuntu, GCC 15:

```
0	-2026.557	-2309.106	282.5493	1	0.00133668	0.00274053	0.000596727	0.000963094	0.000557312	0.00114163	0.00101527	0.00104373	0.00225863	0.00116924	0.00108716	0.000725535	0.000537541	0.00224797	0.000732142	0.000425698	0.00316482	0.00313483	0.00238872	0.000664379	0.00268893	0.000965485	0.000814553	0.000746713	0.00253108	0.00191695	0.00196479	0.00466834	0.00131503	0.00165231	0.0012735	0.00259654	0.00137156	0.00053331	5.63279e-05	0.00135484	0.0025123	0.00121757	0.000955959	0.00199752	0.00126451	0.00242366	0.00353061	2.0803e-05	1.15169e-51	4.04947e-10	2.05509e-08	5.5934e-06	0.0226749	1.09689e-10	0.000145758	0.00947386	4.71519e-11	3.46266e-10	2.44793e-34	0.0050322	0.0221372	0.00344636	1.18957e-20	1.52044e-179	2.57442e-27	4.97346e-32	0.00335607	0.00820008	3.46221e-05	4.17156e-06	8.34824e-08	0.0023077	1.62205e-06	0.000264192	3.74358e-27	1.39068e-26	0.00101172	5.12764e-05	0.00521443	0.00174977	3.34932e-05	0.00130835	0.00197634	0.00117526	0.00166874	0.000308962	0.00140377	0.00169593	0.136954	0.476752	1	2.38629	0.007014646	0.009347597	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.2433663	12.4385	1.58284	1.78309	3.20869	0.763805	3.1913	2.72663	2.72663	0.693887	1.59531	1.59531	1.56161	1.56161	1.57279	1.55081	1.55081	1.58741	1.58741	1.56133	1.56133	2.93436	2.95149	4.50096	4.50662	2.95714	2.93152	4.48099	0.772564	0.754742	0.754742	1.99476	1.25413	2.80129	2.77137	2.74662	2.74662	2.10967	6.23741	6.23741	6.23951	3.06436	3.3516	1.08882	0.285475	0.0121102	0.0247559	0.110993	0.201655	0.0339269	0.00830459	0.0600984	0.0740593	0.0239678	0.10051	0.0187618	0.0553632	0.0374606	0.0111829	0.0259918	0.00347397	0.0448459	0.0182111	2.82199	0.115154	0.56551	0.0786778	0.183833	1.7242	0.148407	1.47849	0.00598896	0.0686728	0.0810727	0.268755	2.75811	3.05822	0.275458	5.05661	2.28923	0.641397	0.928277	0.694271	2.67008	12.3289	0.001364427	0	219.7903	0.003006594	0.979662	2.00855	0.437346	0.705859	0.408458	0.836712	0.744101	0.764961	1.65537	0.856946	0.79679	0.53175	0.393968	1.64755	0.536593	0.311998	2.31952	2.29754	1.75071	0.486929	1.97074	0.707612	0.596993	0.547272	1.85505	1.40495	1.44001	3.42147	0.963798	1.21099	0.933357	1.90302	1.00522	0.390867	0.0412832	0.99297	1.84128	0.892368	0.70063	1.464	0.926768	1.77632	2.58761	0.0152467	8.44081e-49	2.96789e-07	1.50619e-05	0.00409945	16.6186	8.03918e-08	0.106827	6.94347	3.4558e-08	2.53781e-07	1.79411e-31	3.68814	16.2245	2.52587	8.71847e-18	1.11434e-176	1.88682e-24	3.64509e-29	2.45969	6.00991	0.0253748	0.00305737	6.11849e-05	1.69133	0.00118882	0.193628	2.7437e-24	1.01924e-23	0.741501	0.0375809	3.8217	1.28242	0.0245474	0.958903	1.44848	0.861361	1.22304	0.226441	1.02884	1.24296	0.005371509	0.01636224	66	72.1	100.5	72.1	72.1	174.1	157	66	145	89.8	89.8	152.1	86.3	168.3	100.5	100.5	89.8	89.8	66	100.5	66	66	157	83.6	132.9	72.1	89.8	66	66	66	66	66	66	66	66	93.9	89.8	113	83.6	83.6	66	83.6	89.8	0.5712907
5	-1263.78	-1660.667	396.8867	1.950587	0.0200856	0.0555656	0.0214929	0.0249509	0.0137152	0.0226986	0.0278923	0.027849	0.0705266	0.0325132	0.0359719	0.0187866	0.0119122	0.0401022	0.020741	0.0109953	0.0729831	0.0783028	0.09712	0.0179117	0.0694522	0.0260879	0.021039	0.0146292	0.0653749	0.0495126	0.0504124	0.146342	0.0359497	0.0415577	0.032893	0.0826066	0.0354258	0.0167974	0.00133654	0.0305501	0.0462945	0.0314485	0.0282624	0.0402323	0.0326608	0.0626003	0.0986569	0.000421904	3.26955e-50	1.04593e-08	6.12189e-07	0.0001107	0.56042	3.56704e-09	0.00443825	0.181211	1.44016e-09	7.16702e-09	9.31162e-33	0.0981568	0.678005	0.0700644	3.46462e-19	4.65775e-178	6.09828e-26	1.5808e-30	0.0940351	0.222825	0.000764301	0.000127735	2.0275e-06	0.0500521	4.666e-05	0.00678106	6.59024e-26	3.59198e-25	0.0206911	0.000871734	0.112539	0.037688	0.000907935	0.0384767	0.0510467	0.0257485	0.0422341	0.00798016	0.0510319	0.0409304	0.287304	0.649654	1.0687	1.99434	0.007377744	0.1565297	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.1231966	12.0104	1.52836	1.72172	3.09826	0.737517	3.08147	2.63279	2.63279	0.670006	1.54041	1.54041	1.50787	1.50787	1.51866	1.49744	1.49744	1.53278	1.53278	1.5076	1.5076	2.83337	2.84991	4.34605	4.35152	2.85537	2.83063	4.32677	0.745976	0.728767	0.728767	1.92611	1.21096	2.70488	2.67599	2.65209	2.65209	2.03706	6.02275	6.02275	6.02477	2.95889	3.23626	1.05135	0.27565	0.0116934	0.0239039	0.107173	0.194715	0.0327593	0.00801878	0.05803	0.0715105	0.023143	0.0970511	0.0181161	0.0534578	0.0361713	0.0107981	0.0250973	0.00335441	0.0433025	0.0175844	2.72487	0.111191	0.546047	0.07597	0.177506	1.66486	0.143299	1.42761	0.00578284	0.0663094	0.0782825	0.259505	2.66318	2.95297	0.265978	4.88258	2.21044	0.619323	0.896329	0.670377	2.57819	11.9046	0.03524165	2	220.3706	0.02199344	0.56994	1.5767	0.609872	0.707994	0.389177	0.644085	0.791458	0.79023	2.00123	0.92258	1.02072	0.533078	0.338015	1.13792	0.588538	0.311998	2.07093	2.22188	2.75583	0.508254	1.97074	0.740259	0.596993	0.415112	1.85505	1.40495	1.43048	4.15254	1.02009	1.17922	0.933357	2.34401	1.00522	0.476635	0.0379249	0.866875	1.31363	0.892368	0.80196	1.14161	0.926768	1.77632	2.79944	0.0119717	9.27753e-49	2.96789e-07	1.73712e-05	0.00314117	15.9022	1.01217e-07	0.125938	5.14195	4.08653e-08	2.03368e-07	2.64222e-31	2.78525	19.2387	1.98811	9.83103e-18	1.32166e-176	1.73042e-24	4.48561e-29	2.66829	6.32279	0.0216874	0.00362455	5.75314e-05	1.42025	0.001324	0.192416	1.87002e-24	1.01924e-23	0.58712	0.0247359	3.19334	1.06942	0.0257631	1.0918	1.44848	0.730627	1.19841	0.226441	1.44806	1.16142	0.1436852	0.1639074	66	72.26	100.579	73.9622	72.3733	174.438	157.665	66	145.395	89.8996	90.6221	152.833	87.2538	168.868	101.333	100.86	89.9626	90.8686	66	100.623	66	66	157.566	84.1785	133.132	72.2318	89.9566	66	66	66	66	66	66	66	66	93.94	90.3985	113.454	83.7632	83.7113	66	84.2225	90.1521	0.9549884
```

Latest Ubuntu, Clang 15:

```
0	-2134.375	-2376.691	242.3162	1	0.000941988	0.00269374	0.000739394	0.000805488	0.00194853	0.000867063	0.00102343	0.000640193	0.00032503	0.000851253	0.00127665	0.00108601	0.00119809	0.000644953	0.000822798	0.000442464	0.00127489	0.00159845	0.00156627	0.000240128	0.000673678	0.001267	0.000745826	0.000271846	0.0013726	0.00157898	0.00189308	0.000818109	0.000421953	0.000475766	0.000998674	0.000742649	0.000769676	0.00109625	0.000603476	0.000573901	0.000812451	0.00130307	0.00091172	0.000720732	0.00138762	0.00168311	0.00095269	0.000166898	7.76111e-11	2.92399e-08	0.00445321	0.000813087	4.16905e-105	0.0050554	2.5049e-08	1.98626e-14	3.1711e-17	8.00004e-05	0.000719762	4.74704e-10	2.43703e-58	1.22385e-13	0.000808973	5.08764e-06	0.00173691	1.04238e-10	0.000675856	4.86948e-07	0.00146733	0.00199238	8.34824e-05	0.00106761	0.000405439	0.00105435	1.44004e-126	6.34607e-05	0.000322991	0.000123886	0.00143136	0.00149366	0.00126663	0.00108083	0.0013504	0.000767754	0.00144335	0.000437374	0.00131214	0.00098527	0.136954	0.476752	1	2.38629	0.04089133	0.02292314	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.2501437	33.5483	4.26911	4.80923	8.65424	2.06008	8.60734	7.35407	7.35407	1.8715	12.1397	4.24203	4.21111	4.21111	4.18273	4.18273	4.31213	4.30276	4.30276	4.43309	4.28145	4.28145	12.1549	7.97579	7.99819	12.0858	7.90669	7.91434	2.0837	2.03564	2.03564	5.38012	3.38254	7.55544	7.47474	4.59905	7.40797	8.49897	8.25932	16.8231	16.8287	16.8287	9.03971	2.93669	0.769963	0.0326628	0.0667698	0.299362	0.54389	0.00765624	0.083849	0.162093	0.184492	0.0646443	0.200757	0.00936975	0.0199193	0.0291371	0.000750982	0.0301618	0.0900226	0.101036	0.0491177	7.65746	0.264392	1.52525	0.212204	0.495822	4.65038	0.400272	3.98768	0.016153	0.185219	0.218663	0.724867	7.43897	8.24842	0.742945	13.6383	6.17434	1.72993	2.50368	1.87254	7.20155	33.2528	0.001038213	0	223.5693	0.007646904	0.907317	2.5946	0.71218	0.77584	1.87681	0.83515	0.985765	0.61663	0.313067	0.819922	1.22966	1.04604	1.15399	0.621214	0.792513	0.426178	1.22796	1.53961	1.50862	0.23129	0.648883	1.22036	0.718375	0.26184	1.32208	1.52087	1.8234	0.787997	0.406422	0.458255	0.961917	0.715315	0.741346	1.0559	0.581264	0.552778	0.782548	1.25511	0.878162	0.694205	1.33655	1.62116	0.917625	0.160755	7.47545e-08	2.81636e-05	4.2893	0.78316	4.0156e-102	4.86933	2.4127e-05	1.91315e-11	3.05438e-14	0.0770559	0.69327	4.57231e-07	2.34733e-55	1.1788e-10	0.779197	0.00490038	1.67298	1.00402e-07	0.65098	0.000469026	1.41332	1.91905	0.0804097	1.02831	0.390516	1.01555	1.38704e-123	0.0611249	0.311103	0.119326	1.37868	1.43869	1.22001	1.04104	1.3007	0.739495	1.39022	0.421275	1.26385	0.949006	0.001515412	0.06381447	66	72.1	100.5	72.1	72.1	174.1	157	66	145	89.8	89.8	152.1	86.3	168.3	100.5	100.5	89.8	89.8	66	100.5	66	66	157	83.6	132.9	72.1	89.8	66	66	66	66	66	66	66	66	93.9	89.8	113	83.6	83.6	66	83.6	89.8	0.3592154
5	-1387.972	-1669.087	281.1146	3.104472	0.0252053	0.0729658	0.0242845	0.025998	0.0527491	0.0267898	0.0243422	0.0151567	0.00717228	0.0282908	0.0280757	0.0231151	0.0326049	0.0158416	0.022016	0.00950512	0.0524788	0.0379617	0.0352335	0.00512016	0.0183768	0.0332266	0.0190978	0.0103409	0.03143	0.0422497	0.0502753	0.0192755	0.0112904	0.0141021	0.0267221	0.0198715	0.0281805	0.0231319	0.0217793	0.0169026	0.0225402	0.0326885	0.0245085	0.0221632	0.0381892	0.0520924	0.0374006	0.00500917	2.29017e-09	8.22326e-07	0.163237	0.019943	1.11554e-103	0.156984	5.877e-07	5.67069e-13	8.80768e-16	0.00198821	0.0202738	1.28365e-08	6.5136e-57	2.78174e-12	0.0221053	0.000188062	0.0389148	1.86728e-09	0.0198966	1.27444e-05	0.0448276	0.0647693	0.00194319	0.0378395	0.00920862	0.0285746	3.00483e-125	0.00203761	0.00864244	0.00361799	0.0441566	0.0399668	0.0301355	0.0299751	0.0381987	0.0160337	0.0413145	0.0102857	0.0282118	0.0322273	0.397186	0.737153	1.08299	1.78268	0.03861735	0.09383521	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.1779974	26.8933	3.42224	3.85521	6.93748	1.65142	6.89989	5.89523	5.89523	1.50025	9.7315	3.40053	3.37575	3.37575	3.35299	3.35299	3.45673	3.44922	3.44922	3.55369	3.43213	3.43213	9.74373	6.39362	6.41158	9.68833	6.33823	6.34436	1.67036	1.63182	1.63182	4.31286	2.71154	6.05666	5.99197	3.68673	5.93844	6.81302	6.62091	13.4859	13.4904	13.4904	7.24649	2.35413	0.617224	0.0261835	0.0535246	0.239977	0.435998	0.00613746	0.0672157	0.129938	0.147894	0.0518207	0.160932	0.00751106	0.0159679	0.0233571	0.000602008	0.0241786	0.0721647	0.0809933	0.0393742	6.13844	0.211944	1.22269	0.170109	0.397465	3.72787	0.32087	3.19664	0.0129487	0.148477	0.175287	0.581074	5.96329	6.61217	0.595566	10.9329	4.94953	1.38676	2.00702	1.50108	5.77297	26.6564	0.02778004	3	224.0994	0.02031919	0.907317	2.62655	0.874171	0.935854	1.89881	0.964354	0.876249	0.545597	0.258181	1.01839	1.01064	0.832074	1.17368	0.57025	0.792513	0.342156	1.88908	1.36651	1.2683	0.184311	0.661512	1.19606	0.687464	0.372242	1.13139	1.52087	1.80976	0.693862	0.406422	0.507634	0.961917	0.715315	1.01441	0.832682	0.78399	0.608445	0.811382	1.17669	0.882235	0.79781	1.3747	1.87518	1.34631	0.180315	8.24394e-08	2.96013e-05	5.87606	0.717891	4.0156e-102	5.65098	2.11555e-05	2.04128e-11	3.17051e-14	0.0715697	0.729798	4.62078e-07	2.3447e-55	1.00135e-10	0.795727	0.00676968	1.40082	6.72167e-08	0.716219	0.00045876	1.61366	2.33151	0.0699492	1.36211	0.331483	1.0286	1.08165e-123	0.0733479	0.311103	0.130237	1.58951	1.43869	1.08479	1.07902	1.37504	0.577165	1.4872	0.370256	1.01554	1.16009	0.05058293	0.1324526	66	72.3524	100.515	72.787	73.176	174.221	158.305	66	145.14	89.873	90.3104	152.399	86.3246	168.595	102.201	100.813	90.0908	90.2953	66	100.841	66	66	157.775	83.7939	133.587	72.3718	91.4442	66	66	66	66	66	66	66	66	93.9794	89.83	113.144	83.7576	84.1975	66	84.4705	90.1331	0.7084439
```

File: src/core/moves/proposal/tree/FossilTipTimeUniformProposal.cpp [hunk 1]
```diff
@@ -113,7 +111,12 @@ double FossilTipTimeUniformProposal::doProposal( void )
     
     Tree& tau = tree->getValue();
     
-    if ( use_index == false )
+    if ( use_index )
```
Comment (hoehna) [inline src/core/moves/proposal/tree/FossilTipTimeUniformProposal.cpp:114]: Try to add in this if statement to compute the tip index only the first time when this is called.

Comment (davidcerny) [reply src/core/moves/proposal/tree/FossilTipTimeUniformProposal.cpp:114]: As we discussed, I tried to implement your suggestion as follows: let the constructor set the `node_index` to −1 (always), and then use `prepareProposal()` to recalculate it only if it is still equal to that value:

```
if ( tip_taxon == "" )
{
    use_index = false;
    node_index = (size_t)(-1);
}
else
{
    use_index = true;
    node_index = (size_t)(-1);
}
```

and

```

void FossilTipTimeSlideUniformProposal::prepareProposal( void )
{
    if ( use_index && node_index == (size_t)(-1) )
    {
        node_index = tree->getValue().getTipIndex( tip_taxon );
    }
}
```

This didn't work – we still get a mismatch between the taxon and the ages, which causes us to never exit the `while` loop inside `doProposal()`. I agree it would make sense conceptually if the `node_index` computation only needed to happen the first time, so It's not clear to me why this solution didn't work. But it didn't.

**Comment by davidcerny** [comment]
As a bonus, this PR now also fixes #858.

File: src/core/utils/StartingTreeSimulator.cpp [hunk 2]
```diff
@@ -231,8 +229,25 @@ Tree* StartingTreeSimulator::simulateTree( const std::vector<Taxon> &taxa, const
         }
         
         simulateClade(nodes_in_clade, c.getAge());
-        TopologyNode *remaining_node = *(nodes_in_clade.begin());
-        nodes.push_back( remaining_node );
+        
+        // Get the remaining node deterministically by sorting the set
+        std::vector<TopologyNode*> remaining_nodes(nodes_in_clade.begin(), nodes_in_clade.end());
```
Comment (hoehna) [inline src/core/utils/StartingTreeSimulator.cpp]: If there is an issue with the ordering of the nodes based on them being a pointer, I suggest using our 'RbOrderedSet'. This was exactly implemented for his reason.

File: src/core/utils/StartingTreeSimulator.cpp [hunk 3]
```diff
@@ -358,25 +373,40 @@ void StartingTreeSimulator::simulateClade( std::set<TopologyNode*> &nodes, doubl
...
-        std::advance(left_it, left_index);
-        TopologyNode *left = *left_it;
-        current_nodes.erase( left_it );
-        
-        size_t right_index = size_t( current_nodes.size() * rng->uniform01() );
-        std::set<TopologyNode*>::iterator right_it = current_nodes.begin();
-        std::advance(right_it, right_index);
-        TopologyNode *right = *right_it;
-        current_nodes.erase( right_it );
+        // Convert set to sorted vector to ensure node selection is deterministic
```
Comment (hoehna) [inline src/core/utils/StartingTreeSimulator.cpp]: Again, if you could simply use RbOrderedSet

File: src/core/moves/proposal/tree/FossilTipTimeSlideUniformProposal.cpp [hunk 4]
```diff
@@ -114,7 +112,12 @@ double FossilTipTimeSlideUniformProposal::doProposal( void )
     
     Tree& tau = tree->getValue();
     
-    if ( use_index == false )
+    if ( use_index )
+    {
+        // Always recompute node_index
+        node_index = tree->getValue().getTipIndex( tip_taxon );
```
Comment (bredelings) [inline src/core/moves/proposal/tree/FossilTipTimeSlideUniformProposal.cpp:123]: If you want to find out why this is necessary, you could initialize `node_index` before this and then replace the assignment statement with `assert(node_index == tree->getValue().getTipIndex( tip_taxon)`.  

The assert should trigger - if they are always equal the assignment would have no effect.  Then, if you run the code in the  debugger you can observe what the variables look when they are different.  Then you could find out why the assignment is necessary.

Or am I missing something?

Alternatively, you could simply add a print statement that prints `node_index`, `tip_taxon`, and `tree->getValue().getTipIndex( tip_taxon)`.

Comment (davidcerny) [reply src/core/moves/proposal/tree/FossilTipTimeSlideUniformProposal.cpp:123]: Detecting when `node_index` diverges from `tree->getValue().getTipIndex(tip_taxon)` is not the issue. I did that and got the answer: it happens the very first time the proposal is performed in the second run. It never happens in the first run. What I didn't manage to figure out is _why_ this is the case. Something to do with cloning `MonteCarloAnalysis` objects, clearly, but that's as far as I can get.

I didn't try to print the values of `node_index` and `tip_taxon` when the discrepancy arises, that's true. But I can't really see myself being able to infer the cause of the mismatch from knowing which nodes are being mismatched.

**Review by hoehna — APPROVED** [review]
Looks good for now. Still curious if this couldn't be solved on principle.
