### PR TITLE
Make sure `storedNode` is not NULL when undoing node time proposals

### LINKED ISSUE #818: [BUG] Segmentation fault in `mcmc.burnin` with FBD + dnPhyloBrownianREML
**Describe the bug**
Running FBD inference with continuous traits under a BM model, I get "Segmentation fault (core dumped)" during the burnin phase. This does not occur for all seeds.

**To Reproduce**

Minimal example to reproduce the segFault:

[example_data.zip](https://github.com/user-attachments/files/21714014/example_data.zip)

```
seed(10)
cont_char <- readContinuousCharacterData("char_mat_35_nchar30_sigsq0_3_rho1.nex")
taxa = readTaxonData("fossils_35_rho1.csv")

moves    = VectorMoves()
monitors = VectorMonitors()

sigma_square ~ dnExponential(lambda = 1.0)
moves.append( mvScale(sigma_square, weight=1.0, lambda = 0.03) )
moves.append( mvScale(sigma_square, weight=1.0, lambda = 0.1) )
moves.append( mvScale(sigma_square, weight=1.0, lambda = 0.3) )
moves.append( mvScale(sigma_square, weight=1.0, lambda = 1.0) )
moves.append( mvScale(sigma_square, weight=1.0, lambda = 3.0) )
moves.append( mvScale(sigma_square, weight=1.0, lambda = 10.0) )

origin_time <- 2.0
fbd_tree ~ dnFBDP(origin=origin_time, lambda=1.0, mu=0.3, psi=5.0, rho=1.0, taxa=taxa)
moves.append( mvFNPR(fbd_tree, weight=100.0) )
moves.append( mvGPR(fbd_tree, weight = 300.0))
moves.append( mvCollapseExpandFossilBranch(fbd_tree, origin_time, weight=500.0) )
moves.append( mvNodeTimeSlideUniform(fbd_tree, weight=10.0) )
moves.append( mvNodeTimeScale(fbd_tree, weight = 20.0))
moves.append( mvRootTimeSlideUniform(fbd_tree, origin_time, weight=5.0) )
moves.append( mvSubtreeScale(fbd_tree, weight = 10.0))
moves.append( mvTreeScale(fbd_tree, weight = 10.0))

traits ~ dnPhyloBrownianREML(fbd_tree, branchRates=sqrt(sigma_square), nSites=cont_char.nchar())
traits.clamp(cont_char)

my_model = model(sigma_square)

mymcmc = mcmc(my_model, monitors, moves, nruns = 2)
mymcmc.burnin(generations = 20, tuningInterval = 10)

q()
```

**Expected behavior**
Mcmc analysis runs as expected without segfault.

**Computer info**
Running on WSL2 (Ubuntu 24.04.2 LTS), RevBayes version (1.3.0) Build from development (rapture-4174-g376e80) on Thu Jul 31 16:15:21 CEST 2025

### LINKED ISSUE #828: [BUG] SegFault in FBD + Mk analyses
**Describe the bug**
I run a constant rate FBD analysis with the Mk model, setting the initial tree to the "true" tree to help with convergence. During burnin, I get a segmentation fault.

**To Reproduce**

[example_data.zip](https://github.com/user-attachments/files/21964905/example_data.zip)

```
seed(42)
morph_name <- "char_mat_5_nchar300_rho1.nex"
taxa_name <- "fossils_5_nchar300_rho1.csv"
tree_name <- "tree_5_nchar300_rho1.nex" 

morph <- readDiscreteCharacterData(morph_name)
taxa <- readTaxonData(taxa_name)
init_tree <- readTrees(tree_name)[1]

# fossil only fbd inference - constant rates
moves = VectorMoves()

## FBD model with continuous sampling, extinction, and origination
rho <- 1.0
# FBD model with constant sampling, origination, and extinction
speciation_rate ~ dnExponential(lambda = 1.0) # set to true mean
moves.append( mvScale(speciation_rate, weight=5.0, lambda = 1.0) )
moves.append( mvScale(speciation_rate, weight=5.0, lambda = 5.0) )
speciation_rate.setValue(1.0)

extinction_rate ~ dnExponential(lambda = 3.3) # set to true mean
moves.append( mvScale(extinction_rate, weight=5.0, lambda = 1.0) )
moves.append( mvScale(extinction_rate, weight=5.0, lambda = 5.0) )
extinction_rate.setValue(0.3)

origin_time ~ dnExponential(lambda = 1.0, offset = 2.0)
moves.append( mvScale(origin_time, weight=15.0) )
origin_time.setValue(2.0)

psi ~ dnExponential(lambda = 0.2) # set to true mean
moves.append( mvScale( psi, weight = 5.0, lambda = 0.1) )
moves.append( mvScale( psi, weight = 5.0, lambda = 1.0) )
moves.append( mvScale( psi, weight = 5.0, lambda = 10.0) )

fbd_tree ~ dnFBDP(origin=origin_time, lambda=speciation_rate, mu=extinction_rate, psi=psi, rho=rho, taxa=taxa)
fbd_tree.setValue(init_tree)
moves.append( mvFNPR(fbd_tree, weight=200.0) )
moves.append( mvGPR(fbd_tree, weight = 100.0))
moves.append( mvCollapseExpandFossilBranch(fbd_tree, origin_time, weight=500.0) )
moves.append( mvNodeTimeSlideUniform(fbd_tree, weight=100.0) )
moves.append( mvNodeTimeScale(fbd_tree, weight = 200.0))
moves.append( mvRootTimeSlideUniform(fbd_tree, origin_time, weight=50.0) )
moves.append( mvSubtreeScale(fbd_tree, weight = 100.0))
moves.append( mvTreeScale(fbd_tree, origin_time, weight = 100.0))

## other parameters traced
# no sampled ancestors
num_sa := fbd_tree.numSampledAncestors()

# Model of morphological evolution: Mk model without ascertaintment correction
# strict morphological clock
branch_rates_morpho ~ dnExponential(lambda = 10.0)
moves.append( mvScale(branch_rates_morpho, weight = 5.0, lambda = 0.1))
moves.append( mvScale(branch_rates_morpho, weight = 5.0, lambda = 1.0))
moves.append( mvScale(branch_rates_morpho, weight = 5.0, lambda = 10.0))
Q_morpho := fnJC(2)

# combine models
phy_morpho ~ dnPhyloCTMC(tree = fbd_tree, branchRates = branch_rates_morpho, Q = Q_morpho, type = "Standard", coding = "all")
phy_morpho.clamp(morph)

mymodel = model(phy_morpho)
monitors = VectorMonitors()
monitors.append( mnScreen(printgen=1000, origin_time, speciation_rate, extinction_rate) )

mymcmc = mcmc(mymodel, monitors, moves, nruns = 2, ntries = 10000)
mymcmc.burnin(generations=20000,tuningInterval=15000, verbose = TRUE)
mymcmc.operatorSummary()
mymcmc.run(generations=100000)
mymcmc.operatorSummary()

q()
```

**Expected behavior**
Mcmc runs as expected

**Computer info**
Running on WSL2 (Ubuntu 24.04.2 LTS), RevBayes version (1.3.0) Build from development (rapture-4174-g376e80) on Thu Jul 31 16:15:21 CEST 2025

**Additional context**
Potentially linked to #818 , although the setup differs slightly.

### PR DESCRIPTION
**Pull request by davidcerny**
In #798, we allowed for the possibility that some node time moves may find no nodes to operate on. However, this meant the pointer `storedNode` (`stored_node` for `RateAgeBetaShift`) was never initialized, leading to undefined behavior when the `undoProposal()` function tried to dereference it. We now initialize it to `NULL`, and check that it points to an actual node before allowing `undoProposal()` to perform whatever action it wants to perform.

Closes #828.

### CODE REVIEW

File: src/core/moves/compound/RateAgeBetaShift.cpp [hunk 1]
```diff
@@ -502,43 +502,44 @@ void RateAgeBetaShift::printSummary(std::ostream &o, bool current_period) const
...
-    {
-        rates_vec[node_idx]->setValue(new double(stored_rates[node_idx]));
-    }
-    else
-    {
-        rates->getValue()[ node_idx ] = stored_rates[node_idx];
-        rates->touch();
-    }
-    for (size_t i = 0; i < stored_node->getNumberOfChildren(); i++)
+    if (stored_node != NULL)
```
Comment (bredelings) [inline src/core/moves/compound/RateAgeBetaShift.cpp]: I think you could replace this with ` if (stored_node == nullptr) return;`.  Then you wouldn't need to indent everything.

File: src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp [hunk 2]
```diff
@@ -232,19 +232,21 @@ void NodeRateTimeSlideUniformProposal::printParameterSummary(std::ostream &o, bo
...
-    
-    // undo the proposal
-    storedNode->setAge( storedAge );
-    
-    if( rates_node != NULL )
-    {
-        rates_node->getValue() = stored_rates;
-    }
-    else
+    if (storedNode != NULL)
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp]: Also here.

File: src/core/moves/proposal/tree/NodeTimeScaleProposal.cpp [hunk 3]
```diff
@@ -181,10 +181,11 @@ void NodeTimeScaleProposal::printParameterSummary(std::ostream &o, bool name_onl
  */
 void NodeTimeScaleProposal::undoProposal( void )
 {
-    
-    // undo the proposal
-    variable->getValue().getNode( storedNode->getIndex() ).setAge( storedAge );
-    
+    if (storedNode != NULL)
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeTimeScaleProposal.cpp]: And here.

File: src/core/moves/proposal/tree/NodeTimeSlideBetaProposal.cpp [hunk 4]
```diff
@@ -182,10 +182,11 @@ void NodeTimeSlideBetaProposal::printParameterSummary(std::ostream &o, bool name
  */
 void NodeTimeSlideBetaProposal::undoProposal( void )
 {
-    
-    // undo the proposal
-    variable->getValue().getNode( storedNode->getIndex() ).setAge( storedAge );
-    
+    if (storedNode != NULL)
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeTimeSlideBetaProposal.cpp]: And here.

File: src/core/moves/proposal/tree/NodeTimeSlideWeightedProposal.cpp [hunk 5]
```diff
@@ -253,10 +253,11 @@ void NodeTimeSlideWeightedProposal::printParameterSummary(std::ostream &o, bool
  */
 void NodeTimeSlideWeightedProposal::undoProposal( void )
 {
-    
-    // undo the proposal
-    variable->getValue().getNode(storedNode->getIndex()).setAge( storedAge );
-    
+    if (storedNode != NULL)
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeTimeSlideWeightedProposal.cpp]: And here.

File: src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp [hunk 6]
```diff
@@ -373,50 +373,50 @@ void TreeNodeAgeUpdateProposal::printParameterSummary(std::ostream &o, bool name
...
-
-
-    TopologyNode& parent = storedNode->getParent();
-
-    // we need to work with the times
-    double parent_age  = parent.getAge();
-    double my_new_age      = storedNode->getAge();
-    double child_Age   = storedNode->getChild( 0 ).getAge();
-    if ( child_Age < storedNode->getChild( 1 ).getAge())
+    if (storedNode != NULL)
```
Comment (bredelings) [inline src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp]: And here.

**Comment by bredelings** [comment]
Maybe I'm missing something, but it seems like you need to explicitly set `stored_node = nullptr` inside the move or proposal when no node is selected.  Initializing to NULL will initially work because `stored_node` will be `nullptr`, but eventually a proposal will succeed, and the `stored_node` will be set to non-NULL.  Then when a proposal fails after that, `stored_node` won't be set to NULL.

**Comment by davidcerny** [comment]
That's a fair comment about using an early `return;` rather than wrapping everything in an extra condition. I think I was a little traumatized by the discussion we had about #594, where including or not including an empty `return;` seemed to make a difference.

> Maybe I'm missing something, but it seems like you need to explicitly set `stored_node = nullptr` inside the move or proposal when no node is selected. 

That's actually the way I originally did it... let me go back to that, then. Interestingly, it caused a failure in the test added in #798.

> eventually a proposal will succeed, and the `stored_node` will be set to non-NULL. Then when a proposal fails after that, `stored_node` won't be set to NULL.

Ah, I guess I didn't realize that `storedNode` would persist beyond the lifetime of an individual proposal. Would that mean that `undoProposal` would be trying to undo the wrong thing, then? I.e., the last proposal that succeeded in finding an eligible node, as opposed to the one that didn't?

File: src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp [hunk 7]
```diff
@@ -129,6 +129,7 @@ double NodeRateTimeSlideUniformProposal::doProposal( void )
         if (logMCMC >=1 or debugMCMC >=1)
         {
             std::cerr << "mvNodeRateTimeSlideUniform has no effect; the tree only contains the root, tips, and sampled ancestors." << std::endl;
+            storedNode = nullptr;
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp]: I think this should be inside the `node == NULL` check, but outside the `logMCMC >=1 or debugMCMC >=1` check.

File: src/core/moves/proposal/tree/NodeTimeScaleProposal.cpp [hunk 8]
```diff
@@ -105,6 +105,7 @@ double NodeTimeScaleProposal::doProposal( void )
         if (logMCMC >=1 or debugMCMC >=1)
         {
             std::cerr << "mvNodeTimeScale has no effect; the tree only contains the root, tips, and sampled ancestors." << std::endl;
+            storedNode = nullptr;
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeTimeScaleProposal.cpp]: Same here.

File: src/core/moves/proposal/tree/NodeTimeSlideBetaProposal.cpp [hunk 9]
```diff
@@ -104,6 +104,7 @@ double NodeTimeSlideBetaProposal::doProposal( void )
         if (logMCMC >=1 or debugMCMC >=1)
         {
             std::cerr << "mvNodeTimeSlideBeta has no effect; the tree only contains the root, tips, and sampled ancestors." << std::endl;
+            storedNode = nullptr;
```
Comment (bredelings) [inline src/core/moves/proposal/tree/NodeTimeSlideBetaProposal.cpp]: And here.

File: src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp [hunk 10]
```diff
@@ -387,17 +387,17 @@ void TreeNodeAgeUpdateProposal::undoProposal( void )
...
         child_Age = storedNode->getChild( 1 ).getAge();
     }
-
+        
     for ( size_t i=0; i<geneTrees.size(); ++i )
     {
         // get the i-th gene tree
         Tree& geneTree = geneTrees[i]->getValue();
-
+
```
Comment (bredelings) [inline src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp]: Adding a blank line makes sense, but adding a bunch of spaces seems odd?

File: src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp [hunk 11]
```diff
@@ -387,17 +387,17 @@ void TreeNodeAgeUpdateProposal::undoProposal( void )
...
         Tree& geneTree = geneTrees[i]->getValue();
-
+            
         std::vector<TopologyNode*> nodes = getNodesInPopulation(geneTree, *storedNode );
-
+            
         for (size_t j=0; j<nodes.size(); ++j)
         {
-
+
```
Comment (bredelings) [inline src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp]: Why add a blank line here?

File: src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp [hunk 12]
```diff
@@ -408,13 +408,13 @@ void TreeNodeAgeUpdateProposal::undoProposal( void )
             {
                 a = child_Age + (storedAge - child_Age)/(my_new_age - child_Age) * (new_a - child_Age);
             }
-
+                
             // set the new age of this gene tree node
             geneTree.getNode( nodes[j]->getIndex() ).setAge( a );
         }
-
+
```
Comment (bredelings) [inline src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp]: Why add a blank line here? (and funny spaces)

File: src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp (hunk 7 above)
Comment (davidcerny) [reply src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp]: Of course! Fixed now, in all 6 affected moves.

File: src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp (hunk 10 above)
Comment (davidcerny) [reply src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp]: Fixed now.

File: src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp (hunk 12 above)
Comment (davidcerny) [reply src/core/moves/proposal/tree/TreeNodeAgeUpdateProposal.cpp]: Probably an artifact of multiple successive edits... removed.

File: src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp (hunk 7 above)
Comment (davidcerny) [reply src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp]: Apparently this was also the change needed to fix #805!

**Review by bredelings — APPROVED** [review]
